import { Theme, makeStyles } from '@material-ui/core/styles'
import BackgroundImg from '../../assets/images/backImg.png'

export const useStyles = makeStyles((theme: Theme) => ({
  root: {
    width: '100%',
    padding: '0px 12px',
  },
  head: {
    position: 'absolute',
    zIndex: -2,
    left: 0,
    right: 0,
    height: 179,
    backgroundImage: `url(${BackgroundImg})`,
    backgroundRepeat: 'no-repeat',
    backgroundSize: '100% 100%',
  },
  content: {
    '@media (min-width:960px)': {
      flexDirection: 'row',
      padding: '30px 100px 50px',
    },
    '@media (max-width:960px)': {
      flexDirection: 'column',
      padding: '30px 45px 50px',
    },
    // display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  avatarDiv1: {
    width: 166,
    height: 166,
    borderRadius: '50%',
    border: '8px solid white',
    background: '#fff',
    textAlign: 'center',
  },
  avatarDiv: {
    display: 'flex',
    justifyContent: 'center',
  },
  avatar: {
    width: 150,
    height: 150,
    borderRadius: '50%',
    boxShadow: 'rgb(101 52 255 / 15%) 0px 4px 18px 0px',
    maxWidth: '100%',
    verticalAlign: 'middle',
  },
  title: {
    hyphens: 'auto',
    fontSize: 34,
    lineHeight: '50px',
    fontWeight: 600,
    color: '#8076fa',
    marginTop: 8,
    textAlign: 'center',
    wordBreak: 'break-word',
  },
  subContent: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 32,
    position: 'relative',
  },
  image: {
    maxWidth: '100%',
    height: 'auto',
    verticalAlign: 'center',
  },
  div1: {
    display: 'flex',
    flexDirection: 'row',
    gap: 16,
  },
  div2: {
    width: 164,
    height: 83,
    background: '#fff',
    boxShadow: 'rgb(187 196 239 / 35%) 0px 4px 16px 0px',
    borderRadius: '16px',
    padding: '10px',
  },
  h1: {
    marginLeft: 10,
    color: '#6873a4',
    fontSize: 13,
    lineHeight: '28px',
  },
  h2: {
    marginLeft: 36,
    color: '#4d5680',
    fontSize: 26,
    lineHeight: '32px',
  },
  h3: {
    marginTop: 48,
    color: '#8492ce',
    fontSize: 14,
    lineHeight: '20px',
  },
  h4: {
    color: '#6873a4',
    fontSize: 18,
    lineHeight: '28px',
    marginBottom: 16,
  },
  content2: {
    '@media (min-width:960px)': {
      maxWidth: 600,
    },
    '@media (max-width:960px)': {
      maxWidth: '90%',
    },
    margin: '0px auto',
    padding: '50px 0px',
  },
  div3: {
    background: '#fff',
    boxShadow: 'rgb(187 196 239 / 35%) 0px 4px 16px 0px',
    borderRadius: '20px',
  },
  h5: {
    fontSize: 22,
    lineHeight: '27px',
    fontWeight: 600,
    color: '#f9879a',
    textAlign: 'center',
    paddingTop: 40,
  },
  div4: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    textAlign: 'center',
    margin: '32px auto 0px',
    width: '90%',
  },
  input: {
    width: '380px',
    alignItems: 'center',
    outline: 'none',
    appearance: 'none',
    fontSize: '1rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    height: '41px',
    borderRadius: '0.25rem',
    border: '1px solid #7168de',
    background: '#fff',
    color: 'rgb(77, 86, 128)',
    '&.focus-visible': {
      outline: 'none',
    },
  },
  div5: {
    marginTop: 40,
    paddingBottom: '30px',
    textAlign: 'center',
  },
  btn: {
    width: 114,
    height: 39,
    color: '#fff',
    background: '#9289ff',
    boxShadow: 'rgb(101 52 255 / 30%) 0px 6px 18px 0px',
    borderRadius: '50px',
  },
}))
